name: Pulumi
on:
  push:
    branches:
      - Development
jobs:
  build:
    name: build dist
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v3.5.1
        with:
          node-version-file: package.json
      - name: Install npm dependencies
        run: npm install
      - name: Build project
        run: npm run export

  update:
    name: update infrastructure
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v3.5.1
        with:
          node-version-file: package.json
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-region: ${{ secrets.AWS_REGION }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Install npm dependencies
        run: npm install
      - name: Pulumi up
        uses: pulumi/actions@v3
        with:
          work-dir: ./test-aws
          command: up
          stack-name: dev
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}